use_frameworks!

platform :ios, '10.0'

target 'BAlertKit_Example' do
  pod 'BAlertKit/BPopViewManager', :path => '../'
  pod 'Masonry'
  target 'BAlertKit_Tests' do
    inherit! :search_paths

    
  end
end
